### ISSUE TITLE
CMake error: graphicswindow.cpp

### ISSUE THREAD

**Issue by y4my4my4m** [kcat/opendf#15]
I've installed the dependencies and am met with this error when trying to build:

```
→ make                                                                                                                                                                                               [1c5266b]
[ 10%] Built target bsatool
Scanning dependencies of target opendf
[ 12%] Building CXX object CMakeFiles/opendf.dir/src/components/sdlutil/graphicswindow.cpp.o
/home/y4my4m/Dev/opendf/src/components/sdlutil/graphicswindow.cpp: In function ‘void SDLUtil::graphicswindow_SDL2()’:
/home/y4my4m/Dev/opendf/src/components/sdlutil/graphicswindow.cpp:312:27: error: ‘setWindowingSystemInterface’ is not a member of ‘osg::GraphicsContext’
  312 |     osg::GraphicsContext::setWindowingSystemInterface(new SDL2WindowingSystemInterface);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/opendf.dir/build.make:83: CMakeFiles/opendf.dir/src/components/sdlutil/graphicswindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/opendf.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
![image](https://user-images.githubusercontent.com/8145020/85042266-9dbb0180-b150-11ea-9013-ab6c83d7b9be.png)

Any advice?

I'm using arch linux. The dependencies/gcc are all recent/latest versions.

**Comment by psi29a** [comment]
Seems that this is no longer how things are done with OSG 3.4/3.6 (I can reproduce this error with OSG 3.6)

**Comment by y4my4my4m** [comment]
@psi29a I've tried to manually build OSG 3.2 but alas...seems like it coincidentally has a build problem specifically on arch linux.

Let me know if there's an easy fix for OSG 3.6. I'd love to try this out.

**Comment by psi29a** [comment]
Sadly no quick fix that I found. Even OpenMW does things slightly different here.

**Comment by y4my4my4m** [comment]
@psi29a 
I'm not too sure how I did it but I got it to build on OSG3.6
![image](https://user-images.githubusercontent.com/8145020/85801782-37fae680-b709-11ea-97b2-71332d2469fc.png)

I deleted `MYGUI_DBG_BREAK;` from `src/components/mygui_sg/diagnostic.h` and it seems to have helped.

![image](https://user-images.githubusercontent.com/8145020/85801607-d9ce0380-b708-11ea-9856-e1350239d4f2.png)

This is hacky, but figured I'd leave it as a comment in case someone stumble upon this issue later on...

**Comment by psi29a** [comment]
You must have done something else, as doing that for me doesn't change this:

```
/home/psi29a/workspace/opendf/src/components/sdlutil/graphicswindow.cpp: In function ‘void SDLUtil::graphicswindow_SDL2()’:
/home/psi29a/workspace/opendf/src/components/sdlutil/graphicswindow.cpp:312:27: error: ‘setWindowingSystemInterface’ is not a member of ‘osg::GraphicsContext’
     osg::GraphicsContext::setWindowingSystemInterface(new SDL2WindowingSystemInterface);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Are you sure it is OSG 3.6 and not  3.2 or 3.4 ?

**Comment by y4my4my4m** [comment]
@psi29a yes, the difference that I can see is that I did try to build 3.2 manually from cloning the source code on the branch 3.2...
(`git clone --branch OpenSceneGraph-3.2.3 https://github.com/openscenegraph/OpenSceneGraph.git`)

but I never made it past `make` (couldnt get to `make install` as `make` would flood with errors around 30% in) so it would make no sense this helped...right? Unless it installed some dependencies without me noticing?

3.6 was completely uninstalled at this point, after 3.2.3 failing, I reinstalled 3.6 using `pacman`

**Comment by lrustand** [comment]
I made it work with the current OpenSceneGraph. Fixes are in this PR https://github.com/kcat/opendf/pull/16

**Comment by psi29a** [comment]
Also fixed https://github.com/kcat/opendf/pull/18

**Comment by psi29a** [comment]
@kcat can be closed
